const types = {
  CREATE_USER: "CREATE_USER",
  DESTROY_USER: "LOGOUT_USER",

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ADD_FROM_CART: "ADD_FROM_CART",
  CLEAR_ITEM_IN_CART: "CLEAR_ITEM_IN_CART",
  CLEAR_CART: "CLEAR_CART",

  ADD_ADDRESSES: "ADD_ADDRESSES",
  ADD_ADDRESS: "ADD_ADDRESS",
  REMOVE_ADDRESS: "REMOVE_ADDRESS",
  CLEAR_ADDRESSES: "CLEAR_ADDRESSES",

  CHANGE_WELCOME: "CHANGE_WELCOME",
};

export default types;
